### ISSUE TITLE
Design Docs Review #1 - MVP List & Schema

### ISSUE THREAD

**Issue by mmcnulty20** [ligokdoon/Suro#1]
Your design docs are looking great! Here's some minor quibbles and changes you might want to make:
## MVP List
- [x] "Some features" are restricted to signed in users - which features?
- [x] Users can upload images - which users? Just the owner or anyone?
- [x] You could possibly expand out on the search just to make it sound more impressive - mention google maps API integration and consider if you want to include the functionality Turo has where it will automatically search again when you move the map.
- [x] Can you leave reviews for cars you've booked *before* having driven them?
## Schema  
- [x] Index things you may search by frequently, like the longitude and latitude, to speed navigation.
- [x] Could consider factoring things like make/model, as well as features like fuel type, doors, etc out into separate table(s), to facilitate drop-downs and the technically limited possibilities. You have a features table already in the schema for something similar, though this table or these tables may vary a bit from that. (optional)
- [x] Do bookings go through an approval process? If so, you should track the status in the bookings table.
- [x] Should only allow the user to review once per booking. Also, do you want the review to be specifically associated with that individual booking or the car? Talk to me later about why you made the choice you do. 

Overall, great work! with these docs!

**Comment by wilsonli117** [comment]
## MVP LIST

- Clarified which features are restricted to signed in users: (listing a car, making a booking, writing a review)

- Users can only upload photos when listing their car or when they are editing they listing. Only car owners can list photos for their cars.

-  Added Google Maps API integration to CarSearch feature. Search will update as user moves around the Map.

- Clarified that users and hosts can only leave reviews after the start date of their booking.

 ## SCHEMA

-  Added index to longitude and latitude in cars table.

- They car features that I left in the cars table are not user inputted when they list the car. It seems like Turo has their own "dictionary" of cars and they apply those features for the user(make, model, mpg, fuel type). I was going to have a drop down menu for some of those in the listing form, whereas most other features would be a checkbox (my features table would be seeded with 30 or so features) or user inputted (custom features).

-  I hadn't thought about that. Added status column to bookings table.

- Changed reviews table to be polymorphic.

**Comment by mmcnulty20** [comment]
Great work reflecting those suggestions! A few minor additional details
- [x] I could see a value in indexing on reservation dates as well (as often cars will be selected by whether or not they are available in those dates)
- [x] If you *do* want a car "dictionary" with a dropdown, that would probably be its own table. It may be difficult to seed sufficient car types, so we can talk about options here as well.
Again, great job! :) We'll have a discussion about the project, including whether or not you want to implement these, soon.

**Comment by wilsonli117** [comment]
- Added index to start_date and end_date columns in reviews table.

- Upon further research, I think Turo uses the [NHTSA VIN API](https://vpic.nhtsa.dot.gov/api/). Is this something I can use? They have routes for get all makes, get models for make, etc...
